spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
---
spring:
  profiles: mariadb
  datasource:
   hikari:
    driverClassName: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/libaryproject
    username: root
    password: 1234
